allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  esbuild: false
  msgpackr-extract: false
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: false
minimumReleaseAgeExclude:
  - '@tailwindcss/typography@0.5.20'
